name: Publish python package

on:
  push:
    branches:
      - 'releases/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install setuptools and wheel
      run: pip install setuptools wheel

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install --upgrade -r requirements.txt

    - name: Build package
      run: python setup.py --quiet sdist bdist_wheel

    - name: Publish to PyPI (test)
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
